#!/usr/bin/env bash

SCSS='sass --sourcemap=none'
JADE='node_modules/.bin/jade --pretty'

echo build dialog

$SCSS dialog/dialog.scss dialog/dialog.css

echo build popup

$SCSS popup/popup.scss popup/popup.css

echo build process

$SCSS progress/progress.scss progress/progress.css

echo build slide

$SCSS slide/slide.scss slide/slide.css

echo build example

$JADE example/index.jade
